export const MEAL_TYPES = ['Breakfast', 'Lunch', 'Dinner', 'Snacks']

// Common Indian foods — calories/protein/carbs/fat are per defaultServing grams
// unitLabel: human-readable name for 1 serving (shown instead of "1 serving = Xg")
export const INDIAN_FOODS = [
  { name: 'Roti / Chapati',           defaultServing: 40,  unitLabel: '1 roti',              calories: 120, protein: 3,    carbs: 18,   fat: 4    },
  { name: 'Paratha (plain)',           defaultServing: 80,  unitLabel: '1 paratha',           calories: 260, protein: 5,    carbs: 32,   fat: 12   },
  { name: 'Paratha (aloo)',            defaultServing: 100, unitLabel: '1 paratha',           calories: 310, protein: 6,    carbs: 42,   fat: 13   },
  { name: 'Naan',                      defaultServing: 90,  unitLabel: '1 naan',              calories: 270, protein: 8,    carbs: 45,   fat: 6    },
  { name: 'Basmati Rice (cooked)',     defaultServing: 180, calories: 240, protein: 5,    carbs: 52,   fat: 0.5  },
  { name: 'Dal (yellow / moong)',      defaultServing: 240, unitLabel: '1 bowl',              calories: 170, protein: 11,   carbs: 28,   fat: 2    },
  { name: 'Dal Makhani',               defaultServing: 240, unitLabel: '1 bowl',              calories: 230, protein: 11,   carbs: 28,   fat: 8    },
  { name: 'Chana Masala',              defaultServing: 240, unitLabel: '1 bowl',              calories: 270, protein: 14,   carbs: 40,   fat: 7    },
  { name: 'Rajma (kidney beans curry)',defaultServing: 240, unitLabel: '1 bowl',              calories: 250, protein: 13,   carbs: 38,   fat: 5    },
  { name: 'Paneer (raw)',              defaultServing: 100, calories: 265, protein: 18,   carbs: 3,    fat: 20   },
  { name: 'Paneer Butter Masala',      defaultServing: 240, unitLabel: '1 bowl',              calories: 350, protein: 15,   carbs: 12,   fat: 28   },
  { name: 'Palak Paneer',              defaultServing: 240, unitLabel: '1 bowl',              calories: 280, protein: 14,   carbs: 10,   fat: 21   },
  { name: 'Chicken Curry',             defaultServing: 240, unitLabel: '1 bowl',              calories: 300, protein: 28,   carbs: 8,    fat: 18   },
  { name: 'Chicken Tikka Masala',      defaultServing: 240, unitLabel: '1 bowl',              calories: 320, protein: 30,   carbs: 12,   fat: 18   },
  { name: 'Butter Chicken',            defaultServing: 240, unitLabel: '1 bowl',              calories: 340, protein: 28,   carbs: 14,   fat: 20   },
  { name: 'Mutton Curry',              defaultServing: 240, unitLabel: '1 bowl',              calories: 380, protein: 32,   carbs: 6,    fat: 26   },
  { name: 'Fish Curry',                defaultServing: 240, unitLabel: '1 bowl',              calories: 220, protein: 24,   carbs: 8,    fat: 10   },
  { name: 'Samosa (baked)',            defaultServing: 60,  unitLabel: '1 samosa',            calories: 130, protein: 3,    carbs: 18,   fat: 6    },
  { name: 'Samosa (fried)',            defaultServing: 60,  unitLabel: '1 samosa',            calories: 175, protein: 3,    carbs: 20,   fat: 9    },
  { name: 'Idli',                      defaultServing: 80,  unitLabel: '2 idlis',             calories: 130, protein: 4,    carbs: 26,   fat: 1    },
  { name: 'Dosa (plain)',              defaultServing: 80,  unitLabel: '1 dosa',              calories: 170, protein: 4,    carbs: 30,   fat: 4    },
  { name: 'Masala Dosa',              defaultServing: 150, unitLabel: '1 dosa',              calories: 300, protein: 7,    carbs: 50,   fat: 9    },
  { name: 'Poha',                      defaultServing: 160, unitLabel: '1 plate',             calories: 250, protein: 4,    carbs: 45,   fat: 6    },
  { name: 'Upma',                      defaultServing: 200, unitLabel: '1 plate',             calories: 220, protein: 5,    carbs: 38,   fat: 5    },
  { name: 'Biryani (chicken)',         defaultServing: 250, unitLabel: '1 plate',             calories: 400, protein: 20,   carbs: 55,   fat: 12   },
  { name: 'Biryani (veg)',             defaultServing: 250, unitLabel: '1 plate',             calories: 310, protein: 8,    carbs: 58,   fat: 7    },
  { name: 'Aloo Gobi',                 defaultServing: 200, unitLabel: '1 bowl',              calories: 180, protein: 4,    carbs: 28,   fat: 7    },
  { name: 'Bhindi Masala',             defaultServing: 200, unitLabel: '1 bowl',              calories: 160, protein: 4,    carbs: 18,   fat: 9    },
  { name: 'Chole Bhature',             defaultServing: 400, unitLabel: '1 plate',             calories: 620, protein: 18,   carbs: 88,   fat: 22   },
  { name: 'Pav Bhaji',                 defaultServing: 350, unitLabel: '1 plate',             calories: 500, protein: 12,   carbs: 72,   fat: 18   },
  { name: 'Lassi (sweet)',             defaultServing: 250, unitLabel: '1 glass',             calories: 190, protein: 6,    carbs: 28,   fat: 6    },
  { name: 'Lassi (salted)',            defaultServing: 250, unitLabel: '1 glass',             calories: 120, protein: 6,    carbs: 12,   fat: 5    },
  { name: 'Chai (with milk & sugar)', defaultServing: 150, unitLabel: '1 cup',               calories: 60,  protein: 2,    carbs: 8,    fat: 2    },
  { name: 'Raita',                     defaultServing: 120, unitLabel: '1 bowl',              calories: 70,  protein: 3,    carbs: 6,    fat: 3    },
  { name: 'Khichdi',                   defaultServing: 220, unitLabel: '1 bowl',              calories: 280, protein: 10,   carbs: 50,   fat: 4    },
  { name: 'Egg (boiled)',              defaultServing: 50,  unitLabel: '1 egg',               calories: 78,  protein: 6,    carbs: 0.6,  fat: 5    },
  { name: 'Egg Bhurji',               defaultServing: 120, unitLabel: '2 eggs',              calories: 180, protein: 13,   carbs: 4,    fat: 13   },
  { name: 'Dahi (curd / yogurt)',      defaultServing: 240, unitLabel: '1 bowl',              calories: 150, protein: 8,    carbs: 12,   fat: 8    },
  { name: 'Halwa (atta)',              defaultServing: 100, unitLabel: '1 serving',           calories: 350, protein: 5,    carbs: 48,   fat: 16   },
  { name: 'Kheer',                     defaultServing: 200, unitLabel: '1 bowl',              calories: 280, protein: 7,    carbs: 44,   fat: 9    },
  { name: 'Gulab Jamun',              defaultServing: 80,  unitLabel: '2 pieces',            calories: 290, protein: 4,    carbs: 48,   fat: 10   },
  { name: 'Banana',                    defaultServing: 120, unitLabel: '1 banana (medium)',   calories: 105, protein: 1,    carbs: 27,   fat: 0.3  },
  { name: 'Apple',                     defaultServing: 180, unitLabel: '1 apple (medium)',    calories: 95,  protein: 0.5,  carbs: 25,   fat: 0.3  },
  { name: 'Mango',                     defaultServing: 165, unitLabel: '1 cup sliced',        calories: 107, protein: 1,    carbs: 28,   fat: 0.4  },
  { name: 'Whey Protein (scoop)',                       defaultServing: 30,  unitLabel: '1 scoop', calories: 120, protein: 24,   carbs: 3,    fat: 2    },
  { name: 'ON Gold Standard Whey',                      defaultServing: 30,  unitLabel: '1 scoop', calories: 120, protein: 24,   carbs: 3,    fat: 1    },
  { name: 'ON Gold Standard Whey (Double Rich Choc)',   defaultServing: 31,  unitLabel: '1 scoop', calories: 120, protein: 24,   carbs: 4,    fat: 1.5  },
]

export const COMMON_FOODS = [
  // --- Vegetables ---
  { name: 'Broccoli',                  defaultServing: 100, calories: 34,  protein: 2.8,  carbs: 6.6,  fat: 0.4 },
  { name: 'Spinach',                   defaultServing: 100, calories: 23,  protein: 2.9,  carbs: 3.6,  fat: 0.4 },
  { name: 'Cauliflower',               defaultServing: 100, calories: 25,  protein: 1.9,  carbs: 5.0,  fat: 0.3 },
  { name: 'Carrot',                    defaultServing: 100, calories: 41,  protein: 0.9,  carbs: 9.6,  fat: 0.2 },
  { name: 'Tomato',                    defaultServing: 100, calories: 18,  protein: 0.9,  carbs: 3.9,  fat: 0.2 },
  { name: 'Onion',                     defaultServing: 100, calories: 40,  protein: 1.1,  carbs: 9.3,  fat: 0.1 },
  { name: 'Potato (boiled)',           defaultServing: 100, calories: 87,  protein: 1.9,  carbs: 20.0, fat: 0.1 },
  { name: 'Sweet Potato (baked)',      defaultServing: 100, calories: 90,  protein: 2.0,  carbs: 21.0, fat: 0.1 },
  { name: 'Cucumber',                  defaultServing: 100, calories: 16,  protein: 0.7,  carbs: 3.6,  fat: 0.1 },
  { name: 'Bell Pepper',               defaultServing: 100, calories: 31,  protein: 1.0,  carbs: 7.0,  fat: 0.3 },
  { name: 'Cabbage',                   defaultServing: 100, calories: 25,  protein: 1.3,  carbs: 5.8,  fat: 0.1 },
  { name: 'Green Peas',                defaultServing: 100, calories: 81,  protein: 5.4,  carbs: 14.5, fat: 0.4 },
  { name: 'Sweet Corn',                defaultServing: 100, calories: 96,  protein: 3.4,  carbs: 21.0, fat: 1.5 },
  { name: 'Mushroom',                  defaultServing: 100, calories: 22,  protein: 3.1,  carbs: 3.3,  fat: 0.3 },
  { name: 'Zucchini',                  defaultServing: 100, calories: 17,  protein: 1.2,  carbs: 3.1,  fat: 0.3 },
  { name: 'Green Beans',               defaultServing: 100, calories: 31,  protein: 1.8,  carbs: 7.0,  fat: 0.1 },
  { name: 'Kale',                      defaultServing: 100, calories: 49,  protein: 4.3,  carbs: 8.8,  fat: 0.9 },
  { name: 'Beetroot',                  defaultServing: 100, calories: 43,  protein: 1.6,  carbs: 10.0, fat: 0.2 },
  { name: 'Pumpkin',                   defaultServing: 100, calories: 26,  protein: 1.0,  carbs: 6.5,  fat: 0.1 },

  // --- Fruits ---
  { name: 'Orange',                    defaultServing: 130, unitLabel: '1 orange (medium)', calories: 61,  protein: 1.2,  carbs: 15.4, fat: 0.2 },
  { name: 'Grapes',                    defaultServing: 100, calories: 69,  protein: 0.7,  carbs: 18.0, fat: 0.2 },
  { name: 'Watermelon',               defaultServing: 100, calories: 30,  protein: 0.6,  carbs: 7.6,  fat: 0.2 },
  { name: 'Strawberry',               defaultServing: 100, calories: 32,  protein: 0.7,  carbs: 7.7,  fat: 0.3 },
  { name: 'Kiwi',                      defaultServing: 70,  unitLabel: '1 kiwi',           calories: 43,  protein: 0.8,  carbs: 10.1, fat: 0.4 },
  { name: 'Pineapple',                 defaultServing: 100, calories: 50,  protein: 0.5,  carbs: 13.0, fat: 0.1 },
  { name: 'Papaya',                    defaultServing: 100, calories: 43,  protein: 0.5,  carbs: 11.0, fat: 0.3 },
  { name: 'Pomegranate',              defaultServing: 100, calories: 83,  protein: 1.7,  carbs: 19.0, fat: 1.2 },
  { name: 'Guava',                     defaultServing: 100, unitLabel: '1 guava (medium)', calories: 68,  protein: 2.6,  carbs: 14.0, fat: 1.0 },
  { name: 'Pear',                      defaultServing: 180, unitLabel: '1 pear (medium)', calories: 101, protein: 0.7,  carbs: 27.1, fat: 0.2 },
  { name: 'Peach',                     defaultServing: 150, unitLabel: '1 peach',         calories: 59,  protein: 1.4,  carbs: 14.3, fat: 0.4 },
  { name: 'Blueberries',              defaultServing: 100, calories: 57,  protein: 0.7,  carbs: 14.5, fat: 0.3 },
  { name: 'Avocado',                   defaultServing: 100, calories: 160, protein: 2.0,  carbs: 9.0,  fat: 15.0 },

  // --- Proteins (meat / fish) ---
  { name: 'Chicken Breast (cooked)',   defaultServing: 100, calories: 165, protein: 31.0, carbs: 0.0,  fat: 3.6 },
  { name: 'Chicken Breast (raw)',      defaultServing: 100, calories: 120, protein: 22.0, carbs: 0.0,  fat: 2.6 },
  { name: 'Chicken Thigh (cooked)',    defaultServing: 100, calories: 209, protein: 26.0, carbs: 0.0,  fat: 11.0 },
  { name: 'Salmon',                    defaultServing: 100, calories: 208, protein: 20.0, carbs: 0.0,  fat: 13.0 },
  { name: 'Tuna (canned in water)',    defaultServing: 100, calories: 116, protein: 25.5, carbs: 0.0,  fat: 1.0 },
  { name: 'Shrimp (cooked)',           defaultServing: 100, calories: 99,  protein: 24.0, carbs: 0.2,  fat: 0.3 },
  { name: 'Ground Beef (lean)',        defaultServing: 100, calories: 215, protein: 26.0, carbs: 0.0,  fat: 12.0 },

  // --- Eggs & Dairy ---
  { name: 'Egg (whole)',               defaultServing: 50,  unitLabel: '1 egg',           calories: 78,  protein: 6.3,  carbs: 0.6,  fat: 5.3 },
  { name: 'Egg White',                 defaultServing: 33,  unitLabel: '1 egg white',     calories: 17,  protein: 3.6,  carbs: 0.2,  fat: 0.1 },
  { name: 'Greek Yogurt (plain)',      defaultServing: 200, unitLabel: '1 cup',           calories: 130, protein: 22.0, carbs: 9.0,  fat: 0.7 },
  { name: 'Cottage Cheese',            defaultServing: 100, calories: 98,  protein: 11.0, carbs: 3.4,  fat: 4.3 },
  { name: 'Cheddar Cheese',            defaultServing: 100, calories: 402, protein: 25.0, carbs: 1.3,  fat: 33.0 },
  { name: 'Mozzarella',               defaultServing: 100, calories: 280, protein: 28.0, carbs: 3.1,  fat: 17.0 },
  { name: 'Milk (whole)',              defaultServing: 240, unitLabel: '1 cup',           calories: 149, protein: 8.0,  carbs: 11.4, fat: 8.0 },
  { name: 'Milk (skim)',               defaultServing: 240, unitLabel: '1 cup',           calories: 83,  protein: 8.3,  carbs: 12.2, fat: 0.2 },

  // --- Grains & Carbs ---
  { name: 'Oats (dry)',                defaultServing: 40,  unitLabel: '½ cup dry',       calories: 155, protein: 5.4,  carbs: 27.9, fat: 2.7 },
  { name: 'Oatmeal (cooked)',          defaultServing: 240, unitLabel: '1 bowl',          calories: 166, protein: 5.9,  carbs: 28.1, fat: 3.6 },
  { name: 'White Rice (cooked)',       defaultServing: 180, unitLabel: '1 cup',           calories: 234, protein: 4.3,  carbs: 51.8, fat: 0.4 },
  { name: 'Brown Rice (cooked)',       defaultServing: 180, unitLabel: '1 cup',           calories: 218, protein: 4.5,  carbs: 45.8, fat: 1.6 },
  { name: 'Quinoa (cooked)',           defaultServing: 180, unitLabel: '1 cup',           calories: 222, protein: 8.1,  carbs: 39.4, fat: 3.5 },
  { name: 'Pasta (cooked)',            defaultServing: 140, unitLabel: '1 cup',           calories: 220, protein: 8.1,  carbs: 43.2, fat: 1.3 },
  { name: 'Whole Wheat Bread',         defaultServing: 30,  unitLabel: '1 slice',         calories: 69,  protein: 3.6,  carbs: 12.9, fat: 1.1 },
  { name: 'White Bread',               defaultServing: 30,  unitLabel: '1 slice',         calories: 80,  protein: 2.7,  carbs: 15.0, fat: 1.0 },

  // --- Legumes ---
  { name: 'Lentils (cooked)',          defaultServing: 200, unitLabel: '1 cup',           calories: 230, protein: 18.0, carbs: 39.9, fat: 0.8 },
  { name: 'Chickpeas (cooked)',        defaultServing: 164, unitLabel: '1 cup',           calories: 269, protein: 14.5, carbs: 45.0, fat: 4.2 },
  { name: 'Black Beans (cooked)',      defaultServing: 172, unitLabel: '1 cup',           calories: 227, protein: 15.2, carbs: 40.8, fat: 0.9 },
  { name: 'Kidney Beans (cooked)',     defaultServing: 177, unitLabel: '1 cup',           calories: 225, protein: 15.3, carbs: 40.4, fat: 0.9 },
  { name: 'Tofu',                      defaultServing: 100, calories: 76,  protein: 8.1,  carbs: 1.9,  fat: 4.8 },

  // --- Nuts & Fats ---
  { name: 'Almonds',                   defaultServing: 28,  unitLabel: '~23 almonds',     calories: 164, protein: 6.0,  carbs: 6.1,  fat: 14.2 },
  { name: 'Walnuts',                   defaultServing: 28,  unitLabel: '~14 halves',      calories: 185, protein: 4.3,  carbs: 3.9,  fat: 18.5 },
  { name: 'Cashews',                   defaultServing: 28,  unitLabel: '~18 cashews',     calories: 157, protein: 5.2,  carbs: 8.6,  fat: 12.4 },
  { name: 'Peanut Butter',             defaultServing: 32,  unitLabel: '2 tbsp',          calories: 191, protein: 7.1,  carbs: 7.1,  fat: 16.4 },
  { name: 'Olive Oil',                 defaultServing: 14,  unitLabel: '1 tbsp',          calories: 119, protein: 0.0,  carbs: 0.0,  fat: 14.0 },
  { name: 'Butter',                    defaultServing: 14,  unitLabel: '1 tbsp',          calories: 100, protein: 0.1,  carbs: 0.0,  fat: 11.5 },
  { name: 'Coconut Oil',               defaultServing: 14,  unitLabel: '1 tbsp',          calories: 121, protein: 0.0,  carbs: 0.0,  fat: 13.5 },

  // --- American Breakfast ---
  { name: 'Pancake',                   defaultServing: 70,  unitLabel: '1 pancake',       calories: 175, protein: 4.0,  carbs: 27.0, fat: 5.0  },
  { name: 'Waffle',                    defaultServing: 75,  unitLabel: '1 waffle',        calories: 185, protein: 5.0,  carbs: 25.0, fat: 8.0  },
  { name: 'Bacon (cooked)',            defaultServing: 16,  unitLabel: '2 strips',        calories: 87,  protein: 6.0,  carbs: 0.1,  fat: 7.0  },
  { name: 'Sausage Link',              defaultServing: 56,  unitLabel: '2 links',         calories: 170, protein: 8.0,  carbs: 1.0,  fat: 15.0 },
  { name: 'Hash Browns',               defaultServing: 100, calories: 265, protein: 2.0,  carbs: 34.0, fat: 14.0 },
  { name: 'French Toast',              defaultServing: 65,  unitLabel: '1 slice',         calories: 151, protein: 5.0,  carbs: 18.0, fat: 7.0  },
  { name: 'Granola',                   defaultServing: 60,  unitLabel: '½ cup',           calories: 283, protein: 6.0,  carbs: 34.0, fat: 13.0 },
  { name: 'Corn Flakes',               defaultServing: 28,  unitLabel: '1 cup',           calories: 101, protein: 2.0,  carbs: 24.0, fat: 0.2  },
  { name: 'Cheerios',                  defaultServing: 28,  unitLabel: '1 cup',           calories: 100, protein: 3.0,  carbs: 20.0, fat: 2.0  },
  { name: 'Granola Bar',               defaultServing: 47,  unitLabel: '1 bar',           calories: 193, protein: 4.0,  carbs: 29.0, fat: 8.0  },

  // --- Breads & Bakery ---
  { name: 'Bagel',                     defaultServing: 98,  unitLabel: '1 bagel',         calories: 270, protein: 10.0, carbs: 53.0, fat: 1.5  },
  { name: 'English Muffin',            defaultServing: 57,  unitLabel: '1 muffin',        calories: 134, protein: 5.0,  carbs: 26.0, fat: 1.0  },
  { name: 'Croissant',                 defaultServing: 57,  unitLabel: '1 croissant',     calories: 231, protein: 5.0,  carbs: 26.0, fat: 12.0 },
  { name: 'Flour Tortilla',            defaultServing: 45,  unitLabel: '1 medium',        calories: 146, protein: 4.0,  carbs: 25.0, fat: 3.5  },
  { name: 'Corn Tortilla',             defaultServing: 26,  unitLabel: '1 tortilla',      calories: 57,  protein: 1.5,  carbs: 12.0, fat: 0.7  },
  { name: 'Pita Bread',                defaultServing: 60,  unitLabel: '1 pita',          calories: 165, protein: 5.0,  carbs: 33.0, fat: 0.7  },
  { name: 'Blueberry Muffin',          defaultServing: 100, unitLabel: '1 muffin',        calories: 377, protein: 5.0,  carbs: 55.0, fat: 16.0 },
  { name: 'Dinner Roll',               defaultServing: 35,  unitLabel: '1 roll',          calories: 100, protein: 3.0,  carbs: 18.0, fat: 2.0  },

  // --- Proteins (Western) ---
  { name: 'Turkey Breast (cooked)',    defaultServing: 100, calories: 135, protein: 30.0, carbs: 0.0,  fat: 1.0  },
  { name: 'Ham (cooked)',              defaultServing: 100, calories: 145, protein: 20.0, carbs: 1.5,  fat: 7.0  },
  { name: 'Beef Steak (grilled)',      defaultServing: 100, calories: 217, protein: 26.0, carbs: 0.0,  fat: 12.0 },
  { name: 'Pork Chop (cooked)',        defaultServing: 100, calories: 231, protein: 25.0, carbs: 0.0,  fat: 14.0 },
  { name: 'Hot Dog',                   defaultServing: 57,  unitLabel: '1 frank',         calories: 185, protein: 7.0,  carbs: 2.0,  fat: 16.0 },
  { name: 'Beef Jerky',                defaultServing: 28,  unitLabel: '1 oz',            calories: 116, protein: 9.5,  carbs: 3.0,  fat: 7.0  },

  // --- Common Meals ---
  { name: 'Cheeseburger (homemade)',   defaultServing: 150, unitLabel: '1 burger',        calories: 400, protein: 25.0, carbs: 28.0, fat: 21.0 },
  { name: 'Pizza (cheese, 1 slice)',   defaultServing: 107, unitLabel: '1 slice',         calories: 285, protein: 12.0, carbs: 36.0, fat: 10.0 },
  { name: 'Mac and Cheese',            defaultServing: 240, unitLabel: '1 cup',           calories: 390, protein: 14.0, carbs: 48.0, fat: 17.0 },
  { name: 'Chicken Nuggets',           defaultServing: 100, unitLabel: '~6 pieces',       calories: 297, protein: 15.0, carbs: 18.0, fat: 18.0 },
  { name: 'French Fries',              defaultServing: 117, unitLabel: 'medium serving',  calories: 378, protein: 4.0,  carbs: 48.0, fat: 19.0 },
  { name: 'Grilled Cheese Sandwich',   defaultServing: 120, unitLabel: '1 sandwich',      calories: 380, protein: 15.0, carbs: 30.0, fat: 23.0 },
  { name: 'Caesar Salad',              defaultServing: 150, unitLabel: '1 side salad',    calories: 285, protein: 6.0,  carbs: 12.0, fat: 24.0 },
  { name: 'Chicken Sandwich',          defaultServing: 200, unitLabel: '1 sandwich',      calories: 480, protein: 35.0, carbs: 42.0, fat: 19.0 },
  { name: 'Burrito (bean & cheese)',   defaultServing: 220, unitLabel: '1 burrito',       calories: 490, protein: 18.0, carbs: 66.0, fat: 17.0 },
  { name: 'Taco',                      defaultServing: 100, unitLabel: '1 taco',          calories: 226, protein: 12.0, carbs: 20.0, fat: 10.0 },

  // --- Snacks ---
  { name: 'Potato Chips',              defaultServing: 28,  unitLabel: '1 oz',            calories: 152, protein: 2.0,  carbs: 15.0, fat: 10.0 },
  { name: 'Tortilla Chips',            defaultServing: 28,  unitLabel: '1 oz',            calories: 142, protein: 2.0,  carbs: 19.0, fat: 7.0  },
  { name: 'Pretzels',                  defaultServing: 28,  unitLabel: '1 oz',            calories: 108, protein: 3.0,  carbs: 23.0, fat: 1.0  },
  { name: 'Popcorn (air popped)',      defaultServing: 30,  unitLabel: '~3 cups',         calories: 110, protein: 3.5,  carbs: 22.0, fat: 1.3  },
  { name: 'Oreo Cookies',              defaultServing: 34,  unitLabel: '3 cookies',       calories: 160, protein: 1.0,  carbs: 25.0, fat: 7.0  },
  { name: 'Chocolate Bar',             defaultServing: 40,  unitLabel: '1 bar (~40g)',    calories: 214, protein: 3.0,  carbs: 24.0, fat: 12.0 },
  { name: 'Rice Cakes',                defaultServing: 18,  unitLabel: '2 cakes',         calories: 70,  protein: 1.5,  carbs: 15.0, fat: 0.5  },
  { name: 'Protein Bar',               defaultServing: 60,  unitLabel: '1 bar',           calories: 200, protein: 20.0, carbs: 22.0, fat: 7.0  },

  // --- More Dairy ---
  { name: 'Cream Cheese',              defaultServing: 29,  unitLabel: '2 tbsp',          calories: 101, protein: 1.8,  carbs: 1.2,  fat: 10.0 },
  { name: 'Sour Cream',                defaultServing: 30,  unitLabel: '2 tbsp',          calories: 60,  protein: 0.9,  carbs: 1.2,  fat: 5.8  },
  { name: 'Heavy Cream',               defaultServing: 15,  unitLabel: '1 tbsp',          calories: 51,  protein: 0.3,  carbs: 0.4,  fat: 5.5  },
  { name: 'Ice Cream (vanilla)',        defaultServing: 66,  unitLabel: '½ cup',           calories: 145, protein: 2.5,  carbs: 17.0, fat: 8.0  },
  { name: 'American Cheese',           defaultServing: 28,  unitLabel: '1 slice',         calories: 94,  protein: 5.0,  carbs: 1.0,  fat: 7.6  },
  { name: 'Swiss Cheese',              defaultServing: 28,  unitLabel: '1 slice',         calories: 106, protein: 8.0,  carbs: 1.5,  fat: 7.9  },

  // --- Beverages ---
  { name: 'Orange Juice',              defaultServing: 240, unitLabel: '1 cup',           calories: 112, protein: 1.7,  carbs: 26.0, fat: 0.5  },
  { name: 'Apple Juice',               defaultServing: 240, unitLabel: '1 cup',           calories: 114, protein: 0.2,  carbs: 28.0, fat: 0.3  },
  { name: 'Coffee (black)',            defaultServing: 240, unitLabel: '1 cup',           calories: 2,   protein: 0.3,  carbs: 0.0,  fat: 0.0  },
  { name: 'Latte (whole milk)',        defaultServing: 355, unitLabel: '12 oz',           calories: 204, protein: 12.0, carbs: 18.0, fat: 9.0  },
  { name: 'Cola / Soda',               defaultServing: 355, unitLabel: '12 oz can',       calories: 140, protein: 0.0,  carbs: 39.0, fat: 0.0  },
  { name: 'Sports Drink (Gatorade)',   defaultServing: 355, unitLabel: '12 oz',           calories: 80,  protein: 0.0,  carbs: 22.0, fat: 0.0  },
  { name: 'Whole Milk',                defaultServing: 240, unitLabel: '1 cup',           calories: 149, protein: 8.0,  carbs: 11.4, fat: 8.0  },
  { name: 'Almond Milk (unsweetened)', defaultServing: 240, unitLabel: '1 cup',           calories: 30,  protein: 1.0,  carbs: 1.0,  fat: 2.5  },
  { name: 'Protein Shake',             defaultServing: 300, unitLabel: '1 shake',         calories: 160, protein: 25.0, carbs: 8.0,  fat: 3.0  },

  // --- Condiments & Sauces ---
  { name: 'Ketchup',                   defaultServing: 17,  unitLabel: '1 tbsp',          calories: 20,  protein: 0.3,  carbs: 5.0,  fat: 0.0  },
  { name: 'Mayonnaise',                defaultServing: 14,  unitLabel: '1 tbsp',          calories: 94,  protein: 0.1,  carbs: 0.1,  fat: 10.0 },
  { name: 'Ranch Dressing',            defaultServing: 30,  unitLabel: '2 tbsp',          calories: 145, protein: 0.4,  carbs: 1.5,  fat: 15.0 },
  { name: 'Salsa',                     defaultServing: 30,  unitLabel: '2 tbsp',          calories: 10,  protein: 0.4,  carbs: 2.0,  fat: 0.1  },
  { name: 'Hummus',                    defaultServing: 30,  unitLabel: '2 tbsp',          calories: 70,  protein: 2.0,  carbs: 6.0,  fat: 4.5  },
  { name: 'Guacamole',                 defaultServing: 30,  unitLabel: '2 tbsp',          calories: 50,  protein: 0.7,  carbs: 2.5,  fat: 4.5  },
  { name: 'BBQ Sauce',                 defaultServing: 30,  unitLabel: '2 tbsp',          calories: 60,  protein: 0.3,  carbs: 14.0, fat: 0.3  },
  { name: 'Hot Sauce',                 defaultServing: 5,   unitLabel: '1 tsp',           calories: 0,   protein: 0.0,  carbs: 0.1,  fat: 0.0  },

  // ── Chinese ──────────────────────────────────────────────────────────────
  { name: 'Fried Rice (plain)',         defaultServing: 200, unitLabel: '1 cup',           calories: 290, protein: 6.0,  carbs: 45.0, fat: 9.0  },
  { name: 'Chicken Fried Rice',         defaultServing: 200, unitLabel: '1 cup',           calories: 340, protein: 14.0, carbs: 45.0, fat: 11.0 },
  { name: 'Egg Fried Rice',             defaultServing: 200, unitLabel: '1 cup',           calories: 310, protein: 8.0,  carbs: 45.0, fat: 11.0 },
  { name: 'Chow Mein',                  defaultServing: 200, unitLabel: '1 cup',           calories: 290, protein: 11.0, carbs: 40.0, fat: 9.0  },
  { name: 'Lo Mein',                    defaultServing: 200, unitLabel: '1 cup',           calories: 310, protein: 12.0, carbs: 44.0, fat: 9.0  },
  { name: 'Pork Dumpling / Gyoza',      defaultServing: 60,  unitLabel: '3 pieces',        calories: 150, protein: 8.0,  carbs: 16.0, fat: 6.0  },
  { name: 'Steamed Dim Sum (Har Gow)', defaultServing: 75,  unitLabel: '3 pieces',        calories: 115, protein: 7.0,  carbs: 15.0, fat: 3.0  },
  { name: 'Spring Roll (fried)',        defaultServing: 65,  unitLabel: '1 roll',          calories: 163, protein: 4.0,  carbs: 17.0, fat: 9.0  },
  { name: 'Wonton Soup',                defaultServing: 240, unitLabel: '1 bowl',          calories: 100, protein: 7.0,  carbs: 12.0, fat: 2.0  },
  { name: 'Sweet & Sour Chicken',       defaultServing: 200, unitLabel: '1 cup',           calories: 370, protein: 25.0, carbs: 38.0, fat: 12.0 },
  { name: 'Kung Pao Chicken',           defaultServing: 200, unitLabel: '1 cup',           calories: 350, protein: 28.0, carbs: 18.0, fat: 18.0 },
  { name: 'Mapo Tofu',                  defaultServing: 200, unitLabel: '1 cup',           calories: 220, protein: 12.0, carbs: 10.0, fat: 14.0 },
  { name: 'Peking Duck',                defaultServing: 100, calories: 337, protein: 19.0, carbs: 0.0,  fat: 29.0 },

  // ── Japanese ─────────────────────────────────────────────────────────────
  { name: 'Sushi Roll / Maki',          defaultServing: 150, unitLabel: '6 pieces',        calories: 300, protein: 13.0, carbs: 47.0, fat: 6.0  },
  { name: 'Sashimi',                    defaultServing: 100, unitLabel: '6 slices',        calories: 130, protein: 22.0, carbs: 0.0,  fat: 4.0  },
  { name: 'Ramen',                      defaultServing: 500, unitLabel: '1 bowl',          calories: 450, protein: 22.0, carbs: 60.0, fat: 12.0 },
  { name: 'Miso Soup',                  defaultServing: 240, unitLabel: '1 bowl',          calories: 40,  protein: 3.0,  carbs: 5.0,  fat: 1.0  },
  { name: 'Edamame',                    defaultServing: 155, unitLabel: '1 cup',           calories: 188, protein: 17.0, carbs: 14.0, fat: 8.0  },
  { name: 'Teriyaki Chicken',           defaultServing: 100, calories: 200, protein: 24.0, carbs: 8.0,  fat: 8.0  },
  { name: 'Tonkatsu',                   defaultServing: 100, calories: 288, protein: 20.0, carbs: 13.0, fat: 18.0 },
  { name: 'Onigiri',                    defaultServing: 100, unitLabel: '1 rice ball',     calories: 185, protein: 4.0,  carbs: 38.0, fat: 1.0  },
  { name: 'Udon Noodle Soup',           defaultServing: 300, unitLabel: '1 bowl',          calories: 280, protein: 10.0, carbs: 56.0, fat: 2.0  },
  { name: 'Tempura Shrimp',             defaultServing: 90,  unitLabel: '3 pieces',        calories: 216, protein: 11.0, carbs: 18.0, fat: 11.0 },

  // ── Italian ──────────────────────────────────────────────────────────────
  { name: 'Spaghetti Bolognese',        defaultServing: 350, unitLabel: '1 bowl',          calories: 490, protein: 26.0, carbs: 56.0, fat: 16.0 },
  { name: 'Penne Arrabbiata',           defaultServing: 250, unitLabel: '1 bowl',          calories: 350, protein: 12.0, carbs: 60.0, fat: 8.0  },
  { name: 'Pasta Carbonara',            defaultServing: 250, unitLabel: '1 bowl',          calories: 490, protein: 22.0, carbs: 50.0, fat: 22.0 },
  { name: 'Pesto Pasta',                defaultServing: 250, unitLabel: '1 bowl',          calories: 420, protein: 14.0, carbs: 52.0, fat: 18.0 },
  { name: 'Lasagna',                    defaultServing: 250, unitLabel: '1 piece',         calories: 430, protein: 22.0, carbs: 42.0, fat: 18.0 },
  { name: 'Risotto',                    defaultServing: 220, unitLabel: '1 cup',           calories: 310, protein: 8.0,  carbs: 52.0, fat: 8.0  },
  { name: 'Gnocchi',                    defaultServing: 200, unitLabel: '1 cup',           calories: 250, protein: 6.0,  carbs: 50.0, fat: 3.0  },
  { name: 'Minestrone Soup',            defaultServing: 240, unitLabel: '1 bowl',          calories: 80,  protein: 4.0,  carbs: 14.0, fat: 2.0  },
  { name: 'Bruschetta',                 defaultServing: 80,  unitLabel: '2 pieces',        calories: 150, protein: 4.0,  carbs: 22.0, fat: 5.0  },
  { name: 'Tiramisu',                   defaultServing: 100, unitLabel: '1 slice',         calories: 283, protein: 5.0,  carbs: 27.0, fat: 17.0 },

  // ── Mexican ──────────────────────────────────────────────────────────────
  { name: 'Burrito Bowl',               defaultServing: 400, unitLabel: '1 bowl',          calories: 520, protein: 25.0, carbs: 72.0, fat: 14.0 },
  { name: 'Quesadilla',                 defaultServing: 150, unitLabel: '1 large',         calories: 430, protein: 18.0, carbs: 43.0, fat: 21.0 },
  { name: 'Enchilada',                  defaultServing: 180, unitLabel: '1 piece',         calories: 320, protein: 16.0, carbs: 38.0, fat: 12.0 },
  { name: 'Nachos',                     defaultServing: 150, unitLabel: '1 serving',       calories: 480, protein: 14.0, carbs: 52.0, fat: 25.0 },
  { name: 'Tamale',                     defaultServing: 100, unitLabel: '1 tamale',        calories: 220, protein: 6.0,  carbs: 28.0, fat: 10.0 },
  { name: 'Refried Beans',              defaultServing: 120, unitLabel: '½ cup',           calories: 180, protein: 9.0,  carbs: 28.0, fat: 4.0  },
  { name: 'Pico de Gallo',              defaultServing: 30,  unitLabel: '2 tbsp',          calories: 10,  protein: 0.4,  carbs: 2.0,  fat: 0.1  },
  { name: 'Fajita Chicken',             defaultServing: 200, unitLabel: '1 serving',       calories: 350, protein: 30.0, carbs: 22.0, fat: 15.0 },
  { name: 'Churros',                    defaultServing: 50,  unitLabel: '1 churro',        calories: 145, protein: 2.0,  carbs: 22.0, fat: 6.0  },

  // ── Mediterranean ────────────────────────────────────────────────────────
  { name: 'Falafel',                    defaultServing: 90,  unitLabel: '3 pieces',        calories: 195, protein: 8.0,  carbs: 22.0, fat: 9.0  },
  { name: 'Shawarma (chicken wrap)',    defaultServing: 300, unitLabel: '1 wrap',          calories: 500, protein: 28.0, carbs: 52.0, fat: 18.0 },
  { name: 'Tabbouleh',                  defaultServing: 150, unitLabel: '1 cup',           calories: 120, protein: 4.0,  carbs: 15.0, fat: 6.0  },
  { name: 'Greek Salad',                defaultServing: 200, unitLabel: '1 bowl',          calories: 170, protein: 5.0,  carbs: 10.0, fat: 13.0 },
  { name: 'Tzatziki',                   defaultServing: 30,  unitLabel: '2 tbsp',          calories: 25,  protein: 2.0,  carbs: 2.0,  fat: 1.0  },
  { name: 'Shakshuka',                  defaultServing: 250, unitLabel: '1 serving',       calories: 220, protein: 13.0, carbs: 14.0, fat: 12.0 },
  { name: 'Lentil Soup',                defaultServing: 240, unitLabel: '1 bowl',          calories: 130, protein: 9.0,  carbs: 22.0, fat: 2.0  },
  { name: 'Dolma / Stuffed Vine Leaves',defaultServing: 90,  unitLabel: '3 pieces',        calories: 170, protein: 4.0,  carbs: 22.0, fat: 8.0  },
  { name: 'Chicken Kebab',              defaultServing: 100, calories: 185, protein: 22.0, carbs: 3.0,  fat: 10.0 },
  { name: 'Baklava',                    defaultServing: 60,  unitLabel: '1 piece',         calories: 245, protein: 3.0,  carbs: 29.0, fat: 14.0 },

  // ── South Indian ─────────────────────────────────────────────────────────
  { name: 'Sambar',                     defaultServing: 240, unitLabel: '1 bowl',          calories: 120, protein: 6.0,  carbs: 18.0, fat: 3.0  },
  { name: 'Rasam',                      defaultServing: 240, unitLabel: '1 bowl',          calories: 60,  protein: 3.0,  carbs: 9.0,  fat: 2.0  },
  { name: 'Uttapam',                    defaultServing: 120, unitLabel: '1 piece',         calories: 200, protein: 6.0,  carbs: 35.0, fat: 5.0  },
  { name: 'Curd Rice',                  defaultServing: 200, unitLabel: '1 bowl',          calories: 220, protein: 7.0,  carbs: 38.0, fat: 5.0  },
  { name: 'Pongal',                     defaultServing: 200, unitLabel: '1 bowl',          calories: 250, protein: 7.0,  carbs: 42.0, fat: 7.0  },
  { name: 'Medu Vada',                  defaultServing: 60,  unitLabel: '1 vada',          calories: 150, protein: 5.0,  carbs: 18.0, fat: 7.0  },
  { name: 'Appam',                      defaultServing: 60,  unitLabel: '1 appam',         calories: 120, protein: 3.0,  carbs: 22.0, fat: 2.0  },
  { name: 'Avial',                      defaultServing: 200, unitLabel: '1 bowl',          calories: 180, protein: 4.0,  carbs: 16.0, fat: 12.0 },
  { name: 'Coconut Chutney',            defaultServing: 30,  unitLabel: '2 tbsp',          calories: 60,  protein: 1.0,  carbs: 3.0,  fat: 5.0  },

  // ── Gujarati ─────────────────────────────────────────────────────────────
  { name: 'Dhokla',                     defaultServing: 80,  unitLabel: '2 pieces',        calories: 140, protein: 6.0,  carbs: 22.0, fat: 3.0  },
  { name: 'Thepla',                     defaultServing: 50,  unitLabel: '1 thepla',        calories: 130, protein: 3.0,  carbs: 19.0, fat: 5.0  },
  { name: 'Khaman',                     defaultServing: 80,  unitLabel: '2 pieces',        calories: 150, protein: 6.0,  carbs: 24.0, fat: 4.0  },
  { name: 'Khandvi',                    defaultServing: 60,  unitLabel: '3 pieces',        calories: 120, protein: 5.0,  carbs: 18.0, fat: 3.0  },
  { name: 'Handvo',                     defaultServing: 100, unitLabel: '1 slice',         calories: 200, protein: 7.0,  carbs: 30.0, fat: 7.0  },
  { name: 'Dal Dhokli',                 defaultServing: 250, unitLabel: '1 bowl',          calories: 290, protein: 10.0, carbs: 48.0, fat: 7.0  },
  { name: 'Undhiyu',                    defaultServing: 200, unitLabel: '1 bowl',          calories: 280, protein: 8.0,  carbs: 32.0, fat: 14.0 },

  // ── Punjabi Snacks ───────────────────────────────────────────────────────
  { name: 'Aloo Tikki',                 defaultServing: 80,  unitLabel: '1 piece',         calories: 165, protein: 4.0,  carbs: 25.0, fat: 6.0  },
  { name: 'Bhatura',                    defaultServing: 100, unitLabel: '1 bhatura',       calories: 295, protein: 7.0,  carbs: 40.0, fat: 13.0 },
  { name: 'Punjabi Kadhi',              defaultServing: 240, unitLabel: '1 bowl',          calories: 200, protein: 7.0,  carbs: 20.0, fat: 10.0 },
  { name: 'Makki Ki Roti',              defaultServing: 60,  unitLabel: '1 roti',          calories: 165, protein: 3.0,  carbs: 30.0, fat: 4.0  },
  { name: 'Sarson Ka Saag',             defaultServing: 200, unitLabel: '1 bowl',          calories: 180, protein: 6.0,  carbs: 16.0, fat: 11.0 },
  { name: 'Amritsari Kulcha',           defaultServing: 100, unitLabel: '1 kulcha',        calories: 270, protein: 7.0,  carbs: 42.0, fat: 9.0  },
  { name: 'Mathri',                     defaultServing: 40,  unitLabel: '2 pieces',        calories: 175, protein: 3.0,  carbs: 21.0, fat: 9.0  },
  { name: 'Pinni',                      defaultServing: 50,  unitLabel: '1 piece',         calories: 220, protein: 5.0,  carbs: 26.0, fat: 12.0 },

  // ── Fitness — Protein Sources ────────────────────────────────────────────
  { name: 'Casein Protein',             defaultServing: 30,  unitLabel: '1 scoop',         calories: 110, protein: 24.0, carbs: 3.0,  fat: 1.0  },
  { name: 'Plant-based Protein',        defaultServing: 30,  unitLabel: '1 scoop',         calories: 120, protein: 21.0, carbs: 5.0,  fat: 2.0  },
  { name: 'Pea Protein',                defaultServing: 30,  unitLabel: '1 scoop',         calories: 110, protein: 21.0, carbs: 2.0,  fat: 2.0  },
  { name: 'Egg White Protein',          defaultServing: 30,  unitLabel: '1 scoop',         calories: 105, protein: 25.0, carbs: 1.0,  fat: 0.5  },
  { name: 'Collagen Peptides',          defaultServing: 10,  unitLabel: '1 scoop',         calories: 35,  protein: 9.0,  carbs: 0.0,  fat: 0.0  },
  { name: 'Mass Gainer',                defaultServing: 100, unitLabel: '1 scoop',         calories: 380, protein: 30.0, carbs: 60.0, fat: 5.0  },
  { name: 'Tempeh',                     defaultServing: 100, calories: 193, protein: 19.0, carbs: 9.0,  fat: 11.0 },
  { name: 'Seitan',                     defaultServing: 100, calories: 370, protein: 75.0, carbs: 14.0, fat: 2.0  },
  { name: 'Smoked Salmon',              defaultServing: 100, calories: 117, protein: 18.0, carbs: 0.0,  fat: 5.0  },
  { name: 'Sardines (canned)',          defaultServing: 100, calories: 208, protein: 25.0, carbs: 0.0,  fat: 11.0 },
  { name: 'String Cheese',              defaultServing: 28,  unitLabel: '1 stick',         calories: 80,  protein: 7.0,  carbs: 1.0,  fat: 5.0  },

  // ── Fitness — Performance & Supplements ──────────────────────────────────
  { name: 'Creatine',                   defaultServing: 5,   unitLabel: '1 tsp',           calories: 0,   protein: 0.0,  carbs: 0.0,  fat: 0.0  },
  { name: 'BCAA Powder',                defaultServing: 7,   unitLabel: '1 scoop',         calories: 20,  protein: 5.0,  carbs: 0.0,  fat: 0.0  },
  { name: 'Pre-workout',                defaultServing: 10,  unitLabel: '1 scoop',         calories: 20,  protein: 0.0,  carbs: 4.0,  fat: 0.0  },
  { name: 'Energy Gel',                 defaultServing: 32,  unitLabel: '1 packet',        calories: 100, protein: 0.0,  carbs: 25.0, fat: 0.0  },
  { name: 'Dates',                      defaultServing: 24,  unitLabel: '3 dates',         calories: 67,  protein: 0.4,  carbs: 18.0, fat: 0.1  },
  { name: 'Clif Bar',                   defaultServing: 68,  unitLabel: '1 bar',           calories: 250, protein: 9.0,  carbs: 45.0, fat: 5.0  },

  // ── Maharashtrian ────────────────────────────────────────────────────────
  { name: 'Vada Pav',                   defaultServing: 150, unitLabel: '1 vada pav',      calories: 290, protein: 7.0,  carbs: 44.0, fat: 10.0 },
  { name: 'Misal Pav',                  defaultServing: 300, unitLabel: '1 plate',          calories: 380, protein: 14.0, carbs: 58.0, fat: 11.0 },
  { name: 'Puran Poli',                 defaultServing: 80,  unitLabel: '1 poli',           calories: 240, protein: 5.0,  carbs: 45.0, fat: 5.0  },
  { name: 'Sabudana Khichdi',           defaultServing: 200, unitLabel: '1 plate',          calories: 330, protein: 5.0,  carbs: 55.0, fat: 10.0 },
  { name: 'Batata Vada',                defaultServing: 80,  unitLabel: '1 piece',          calories: 175, protein: 3.0,  carbs: 26.0, fat: 7.0  },
  { name: 'Kothimbir Vadi',             defaultServing: 100, unitLabel: '4 pieces',         calories: 210, protein: 6.0,  carbs: 28.0, fat: 9.0  },
  { name: 'Thalipeeth',                 defaultServing: 80,  unitLabel: '1 thalipeeth',     calories: 200, protein: 6.0,  carbs: 30.0, fat: 7.0  },
  { name: 'Bharli Vangi',               defaultServing: 200, unitLabel: '1 bowl',           calories: 180, protein: 4.0,  carbs: 16.0, fat: 11.0 },
  { name: 'Pitla Bhakri',               defaultServing: 200, unitLabel: '1 plate',          calories: 310, protein: 10.0, carbs: 48.0, fat: 9.0  },
  { name: 'Shrikhand',                  defaultServing: 100, unitLabel: '1 serving',        calories: 230, protein: 5.0,  carbs: 40.0, fat: 6.0  },
  { name: 'Basundi',                    defaultServing: 150, unitLabel: '1 bowl',           calories: 260, protein: 7.0,  carbs: 36.0, fat: 10.0 },
  { name: 'Modak (steamed)',            defaultServing: 60,  unitLabel: '2 modak',          calories: 160, protein: 3.0,  carbs: 30.0, fat: 4.0  },
  { name: 'Modak (fried)',              defaultServing: 60,  unitLabel: '2 modak',          calories: 220, protein: 3.0,  carbs: 30.0, fat: 10.0 },
  { name: 'Amboli',                     defaultServing: 80,  unitLabel: '1 amboli',         calories: 150, protein: 4.0,  carbs: 27.0, fat: 3.0  },
  { name: 'Sol Kadhi',                  defaultServing: 200, unitLabel: '1 glass',          calories: 60,  protein: 1.0,  carbs: 8.0,  fat: 3.0  },
  { name: 'Kolhapuri Mutton',           defaultServing: 240, unitLabel: '1 bowl',           calories: 420, protein: 34.0, carbs: 8.0,  fat: 28.0 },
  { name: 'Bhakri (jowar)',             defaultServing: 60,  unitLabel: '1 bhakri',         calories: 130, protein: 3.5,  carbs: 26.0, fat: 1.5  },
  { name: 'Zunka',                      defaultServing: 150, unitLabel: '1 bowl',           calories: 170, protein: 8.0,  carbs: 20.0, fat: 7.0  },
  { name: 'Sabudana Vada',              defaultServing: 60,  unitLabel: '1 vada',           calories: 160, protein: 3.0,  carbs: 22.0, fat: 7.0  },

  // ── Indian Street Food ───────────────────────────────────────────────────
  { name: 'Pani Puri',                  defaultServing: 100, unitLabel: '6 pieces',         calories: 180, protein: 4.0,  carbs: 30.0, fat: 5.0  },
  { name: 'Bhel Puri',                  defaultServing: 150, unitLabel: '1 plate',          calories: 200, protein: 5.0,  carbs: 36.0, fat: 4.0  },
  { name: 'Sev Puri',                   defaultServing: 150, unitLabel: '1 plate',          calories: 250, protein: 5.0,  carbs: 38.0, fat: 9.0  },
  { name: 'Dahi Puri',                  defaultServing: 150, unitLabel: '6 pieces',         calories: 220, protein: 6.0,  carbs: 34.0, fat: 6.0  },
  { name: 'Ragda Pattice',              defaultServing: 250, unitLabel: '1 plate',          calories: 360, protein: 11.0, carbs: 58.0, fat: 10.0 },
  { name: 'Dabeli',                     defaultServing: 120, unitLabel: '1 dabeli',         calories: 260, protein: 6.0,  carbs: 42.0, fat: 8.0  },
  { name: 'Kachori',                    defaultServing: 70,  unitLabel: '1 kachori',        calories: 220, protein: 5.0,  carbs: 26.0, fat: 11.0 },
  { name: 'Chaat (aloo)',               defaultServing: 200, unitLabel: '1 plate',          calories: 280, protein: 6.0,  carbs: 48.0, fat: 8.0  },
  { name: 'Papdi Chaat',                defaultServing: 150, unitLabel: '1 plate',          calories: 240, protein: 6.0,  carbs: 36.0, fat: 8.0  },
  { name: 'Frankie / Kathi Roll',       defaultServing: 200, unitLabel: '1 roll',           calories: 350, protein: 14.0, carbs: 50.0, fat: 11.0 },

  // ── More Indian Mains ────────────────────────────────────────────────────
  { name: 'Tandoori Chicken',           defaultServing: 200, unitLabel: '2 pieces',         calories: 280, protein: 36.0, carbs: 4.0,  fat: 13.0 },
  { name: 'Kadhai Paneer',              defaultServing: 240, unitLabel: '1 bowl',           calories: 310, protein: 14.0, carbs: 14.0, fat: 23.0 },
  { name: 'Matar Paneer',              defaultServing: 240, unitLabel: '1 bowl',           calories: 280, protein: 13.0, carbs: 16.0, fat: 19.0 },
  { name: 'Dal Tadka',                  defaultServing: 240, unitLabel: '1 bowl',           calories: 180, protein: 10.0, carbs: 26.0, fat: 5.0  },
  { name: 'Egg Curry',                  defaultServing: 240, unitLabel: '1 bowl',           calories: 260, protein: 16.0, carbs: 8.0,  fat: 18.0 },
  { name: 'Chicken 65',                 defaultServing: 150, unitLabel: '1 plate',          calories: 310, protein: 26.0, carbs: 12.0, fat: 18.0 },
  { name: 'Mango Pickle (achar)',       defaultServing: 20,  unitLabel: '1 tbsp',           calories: 40,  protein: 0.3,  carbs: 3.0,  fat: 3.0  },
  { name: 'Papad',                      defaultServing: 15,  unitLabel: '1 papad',          calories: 55,  protein: 3.0,  carbs: 8.0,  fat: 1.5  },
  { name: 'Chana Dal',                  defaultServing: 240, unitLabel: '1 bowl',           calories: 220, protein: 13.0, carbs: 34.0, fat: 4.0  },
  { name: 'Kadhi (Punjabi)',            defaultServing: 240, unitLabel: '1 bowl',           calories: 190, protein: 6.0,  carbs: 18.0, fat: 10.0 },

  // ── Indian Sweets ────────────────────────────────────────────────────────
  { name: 'Ladoo (besan)',              defaultServing: 50,  unitLabel: '1 ladoo',          calories: 220, protein: 4.0,  carbs: 28.0, fat: 11.0 },
  { name: 'Barfi (milk)',               defaultServing: 40,  unitLabel: '1 piece',          calories: 170, protein: 4.0,  carbs: 24.0, fat: 7.0  },
  { name: 'Jalebi',                     defaultServing: 60,  unitLabel: '4 pieces',         calories: 200, protein: 2.0,  carbs: 40.0, fat: 4.0  },
  { name: 'Rasmalai',                   defaultServing: 100, unitLabel: '2 pieces',         calories: 185, protein: 6.0,  carbs: 24.0, fat: 8.0  },
  { name: 'Rasgulla',                   defaultServing: 100, unitLabel: '2 pieces',         calories: 150, protein: 4.0,  carbs: 30.0, fat: 2.0  },
  { name: 'Payasam / Kheer',            defaultServing: 200, unitLabel: '1 bowl',           calories: 270, protein: 7.0,  carbs: 42.0, fat: 9.0  },
  { name: 'Imarti',                     defaultServing: 60,  unitLabel: '1 piece',          calories: 190, protein: 3.0,  carbs: 38.0, fat: 3.5  },
  { name: 'Chakli',                     defaultServing: 40,  unitLabel: '4 pieces',         calories: 180, protein: 3.0,  carbs: 22.0, fat: 9.0  },

  // ── Korean ───────────────────────────────────────────────────────────────
  { name: 'Bibimbap',                   defaultServing: 400, unitLabel: '1 bowl',           calories: 490, protein: 22.0, carbs: 72.0, fat: 12.0 },
  { name: 'Kimchi',                     defaultServing: 100, calories: 23,  protein: 1.7,  carbs: 4.0,  fat: 0.5 },
  { name: 'Tteokbokki',                 defaultServing: 200, unitLabel: '1 serving',        calories: 320, protein: 8.0,  carbs: 62.0, fat: 4.0  },
  { name: 'Korean Fried Chicken',       defaultServing: 200, unitLabel: '1 serving',        calories: 480, protein: 30.0, carbs: 28.0, fat: 28.0 },
  { name: 'Bulgogi',                    defaultServing: 200, unitLabel: '1 serving',        calories: 300, protein: 28.0, carbs: 12.0, fat: 16.0 },
  { name: 'Japchae',                    defaultServing: 200, unitLabel: '1 serving',        calories: 290, protein: 10.0, carbs: 46.0, fat: 7.0  },
  { name: 'Kimbap',                     defaultServing: 200, unitLabel: '1 roll (8 pcs)',   calories: 320, protein: 12.0, carbs: 50.0, fat: 7.0  },
  { name: 'Sundubu Jjigae',             defaultServing: 400, unitLabel: '1 bowl',           calories: 220, protein: 14.0, carbs: 10.0, fat: 12.0 },
  { name: 'Doenjang Jjigae',            defaultServing: 300, unitLabel: '1 bowl',           calories: 130, protein: 9.0,  carbs: 8.0,  fat: 6.0  },
  { name: 'Ramyeon (instant)',           defaultServing: 120, unitLabel: '1 pack (dry)',     calories: 500, protein: 10.0, carbs: 72.0, fat: 18.0 },
  { name: 'Samgyeopsal (grilled pork)', defaultServing: 150, unitLabel: '1 serving',        calories: 430, protein: 24.0, carbs: 0.0,  fat: 37.0 },
  { name: 'Dakgalbi',                   defaultServing: 200, unitLabel: '1 serving',        calories: 320, protein: 28.0, carbs: 22.0, fat: 12.0 },

  // ── Thai ─────────────────────────────────────────────────────────────────
  { name: 'Pad Thai',                   defaultServing: 300, unitLabel: '1 plate',          calories: 430, protein: 20.0, carbs: 58.0, fat: 12.0 },
  { name: 'Green Curry (chicken)',      defaultServing: 300, unitLabel: '1 bowl',           calories: 380, protein: 22.0, carbs: 14.0, fat: 26.0 },
  { name: 'Red Curry (chicken)',        defaultServing: 300, unitLabel: '1 bowl',           calories: 360, protein: 22.0, carbs: 12.0, fat: 24.0 },
  { name: 'Tom Yum Soup',               defaultServing: 300, unitLabel: '1 bowl',           calories: 100, protein: 9.0,  carbs: 8.0,  fat: 3.0  },
  { name: 'Som Tum (papaya salad)',     defaultServing: 200, unitLabel: '1 plate',          calories: 130, protein: 5.0,  carbs: 22.0, fat: 3.0  },
  { name: 'Massaman Curry',             defaultServing: 300, unitLabel: '1 bowl',           calories: 420, protein: 18.0, carbs: 28.0, fat: 26.0 },
  { name: 'Pad See Ew',                 defaultServing: 300, unitLabel: '1 plate',          calories: 420, protein: 20.0, carbs: 58.0, fat: 10.0 },
  { name: 'Khao Pad (Thai fried rice)', defaultServing: 250, unitLabel: '1 plate',          calories: 380, protein: 14.0, carbs: 58.0, fat: 10.0 },
  { name: 'Mango Sticky Rice',          defaultServing: 200, unitLabel: '1 serving',        calories: 380, protein: 5.0,  carbs: 72.0, fat: 9.0  },
  { name: 'Tom Kha Gai',               defaultServing: 300, unitLabel: '1 bowl',           calories: 200, protein: 14.0, carbs: 8.0,  fat: 13.0 },

  // ── More Beverages ───────────────────────────────────────────────────────
  { name: 'Green Tea',                  defaultServing: 240, unitLabel: '1 cup',            calories: 2,   protein: 0.0,  carbs: 0.5,  fat: 0.0  },
  { name: 'Matcha Latte',               defaultServing: 355, unitLabel: '12 oz',            calories: 190, protein: 9.0,  carbs: 25.0, fat: 6.0  },
  { name: 'Coconut Water',              defaultServing: 240, unitLabel: '1 cup',            calories: 46,  protein: 1.7,  carbs: 9.0,  fat: 0.5  },
  { name: 'Buttermilk (chaas)',         defaultServing: 240, unitLabel: '1 glass',          calories: 50,  protein: 3.5,  carbs: 5.0,  fat: 1.0  },
  { name: 'Mango Juice',               defaultServing: 240, unitLabel: '1 glass',          calories: 130, protein: 0.8,  carbs: 32.0, fat: 0.3  },
  { name: 'Energy Drink (250ml)',       defaultServing: 250, unitLabel: '1 can',            calories: 110, protein: 1.0,  carbs: 27.0, fat: 0.0  },
  { name: 'Cold Coffee',               defaultServing: 300, unitLabel: '1 glass',          calories: 180, protein: 6.0,  carbs: 26.0, fat: 5.0  },
  { name: 'Nimbu Pani (lemonade)',      defaultServing: 240, unitLabel: '1 glass',          calories: 60,  protein: 0.2,  carbs: 16.0, fat: 0.0  },
  { name: 'Banana Smoothie',            defaultServing: 350, unitLabel: '1 glass',          calories: 240, protein: 8.0,  carbs: 44.0, fat: 4.0  },
  { name: 'Berry Smoothie',             defaultServing: 350, unitLabel: '1 glass',          calories: 190, protein: 5.0,  carbs: 38.0, fat: 2.0  },
  { name: 'Kombucha',                   defaultServing: 240, unitLabel: '1 cup',            calories: 30,  protein: 0.0,  carbs: 7.0,  fat: 0.0  },
  { name: 'Herbal Tea',                 defaultServing: 240, unitLabel: '1 cup',            calories: 2,   protein: 0.0,  carbs: 0.4,  fat: 0.0  },
  { name: 'Soy Milk',                   defaultServing: 240, unitLabel: '1 cup',            calories: 105, protein: 6.3,  carbs: 12.0, fat: 3.5  },
  { name: 'Oat Milk',                   defaultServing: 240, unitLabel: '1 cup',            calories: 120, protein: 3.0,  carbs: 16.0, fat: 5.0  },

  // ── More Fruits ──────────────────────────────────────────────────────────
  { name: 'Raspberries',                defaultServing: 100, calories: 52,  protein: 1.2,  carbs: 11.9, fat: 0.7 },
  { name: 'Blackberries',               defaultServing: 100, calories: 43,  protein: 1.4,  carbs: 9.6,  fat: 0.5 },
  { name: 'Cherries',                   defaultServing: 100, calories: 63,  protein: 1.1,  carbs: 16.0, fat: 0.2 },
  { name: 'Dragon Fruit',               defaultServing: 100, calories: 60,  protein: 1.2,  carbs: 13.0, fat: 0.4 },
  { name: 'Lychee',                     defaultServing: 100, calories: 66,  protein: 0.8,  carbs: 16.5, fat: 0.4 },
  { name: 'Jackfruit',                  defaultServing: 100, calories: 95,  protein: 1.7,  carbs: 23.2, fat: 0.6 },
  { name: 'Fig',                        defaultServing: 50,  unitLabel: '1 fig',            calories: 37,  protein: 0.4,  carbs: 9.6,  fat: 0.1 },
  { name: 'Apricot',                    defaultServing: 35,  unitLabel: '1 apricot',        calories: 17,  protein: 0.5,  carbs: 3.9,  fat: 0.1 },
  { name: 'Plum',                       defaultServing: 66,  unitLabel: '1 plum',           calories: 30,  protein: 0.5,  carbs: 7.5,  fat: 0.2 },
  { name: 'Cranberries (fresh)',        defaultServing: 100, calories: 46,  protein: 0.4,  carbs: 12.2, fat: 0.1 },
  { name: 'Coconut (raw)',              defaultServing: 100, calories: 354, protein: 3.3,  carbs: 15.2, fat: 33.5 },
  { name: 'Passion Fruit',              defaultServing: 18,  unitLabel: '1 fruit',          calories: 17,  protein: 0.4,  carbs: 4.2,  fat: 0.1 },

  // ── More Vegetables ──────────────────────────────────────────────────────
  { name: 'Asparagus',                  defaultServing: 100, calories: 20,  protein: 2.2,  carbs: 3.9,  fat: 0.1 },
  { name: 'Brussels Sprouts',           defaultServing: 100, calories: 43,  protein: 3.4,  carbs: 8.9,  fat: 0.3 },
  { name: 'Celery',                     defaultServing: 100, calories: 16,  protein: 0.7,  carbs: 3.0,  fat: 0.2 },
  { name: 'Radish',                     defaultServing: 100, calories: 16,  protein: 0.7,  carbs: 3.4,  fat: 0.1 },
  { name: 'Spring Onion / Scallion',    defaultServing: 100, calories: 32,  protein: 1.8,  carbs: 7.3,  fat: 0.2 },
  { name: 'Leek',                       defaultServing: 100, calories: 61,  protein: 1.5,  carbs: 14.2, fat: 0.3 },
  { name: 'Eggplant / Brinjal',        defaultServing: 100, calories: 25,  protein: 1.0,  carbs: 5.9,  fat: 0.2 },
  { name: 'Artichoke',                  defaultServing: 120, unitLabel: '1 medium',         calories: 60,  protein: 4.2,  carbs: 13.4, fat: 0.2 },
  { name: 'Bok Choy',                   defaultServing: 100, calories: 13,  protein: 1.5,  carbs: 2.2,  fat: 0.2 },
  { name: 'Coriander / Cilantro',      defaultServing: 10,  unitLabel: '1 handful',        calories: 2,   protein: 0.2,  carbs: 0.3,  fat: 0.0 },
  { name: 'Garlic',                     defaultServing: 9,   unitLabel: '3 cloves',         calories: 13,  protein: 0.6,  carbs: 3.0,  fat: 0.0 },
  { name: 'Ginger',                     defaultServing: 5,   unitLabel: '1 tsp grated',     calories: 4,   protein: 0.1,  carbs: 0.8,  fat: 0.0 },

  // ── More Proteins ────────────────────────────────────────────────────────
  { name: 'Cod (cooked)',               defaultServing: 100, calories: 105, protein: 23.0, carbs: 0.0,  fat: 0.9 },
  { name: 'Tilapia (cooked)',           defaultServing: 100, calories: 128, protein: 26.2, carbs: 0.0,  fat: 2.7 },
  { name: 'Halibut (cooked)',           defaultServing: 100, calories: 140, protein: 27.0, carbs: 0.0,  fat: 3.0 },
  { name: 'Mahi Mahi',                  defaultServing: 100, calories: 109, protein: 24.0, carbs: 0.0,  fat: 0.9 },
  { name: 'Lamb Chop (cooked)',         defaultServing: 100, calories: 294, protein: 25.0, carbs: 0.0,  fat: 21.0 },
  { name: 'Duck Breast (cooked)',       defaultServing: 100, calories: 201, protein: 28.0, carbs: 0.0,  fat: 10.0 },
  { name: 'Liver (chicken)',            defaultServing: 100, calories: 172, protein: 27.0, carbs: 1.0,  fat: 6.5 },
  { name: 'Crab (cooked)',              defaultServing: 100, calories: 97,  protein: 19.4, carbs: 0.0,  fat: 1.5 },
  { name: 'Lobster (cooked)',           defaultServing: 100, calories: 98,  protein: 21.0, carbs: 0.5,  fat: 0.6 },

  // ── Nuts, Seeds & Spreads ────────────────────────────────────────────────
  { name: 'Chia Seeds',                 defaultServing: 28,  unitLabel: '2 tbsp',           calories: 138, protein: 4.7,  carbs: 12.0, fat: 8.7  },
  { name: 'Flax Seeds',                 defaultServing: 14,  unitLabel: '1 tbsp',           calories: 75,  protein: 2.6,  carbs: 4.1,  fat: 5.9  },
  { name: 'Sunflower Seeds',            defaultServing: 28,  unitLabel: '1 oz',             calories: 164, protein: 5.8,  carbs: 6.1,  fat: 14.0 },
  { name: 'Pumpkin Seeds',              defaultServing: 28,  unitLabel: '1 oz',             calories: 151, protein: 7.0,  carbs: 5.0,  fat: 13.0 },
  { name: 'Hemp Seeds',                 defaultServing: 28,  unitLabel: '3 tbsp',           calories: 155, protein: 8.8,  carbs: 2.6,  fat: 12.0 },
  { name: 'Almond Butter',              defaultServing: 32,  unitLabel: '2 tbsp',           calories: 196, protein: 6.7,  carbs: 7.2,  fat: 17.8 },
  { name: 'Tahini',                     defaultServing: 15,  unitLabel: '1 tbsp',           calories: 89,  protein: 2.6,  carbs: 3.2,  fat: 8.0  },
  { name: 'Trail Mix',                  defaultServing: 40,  unitLabel: '¼ cup',            calories: 173, protein: 4.5,  carbs: 17.0, fat: 10.0 },
  { name: 'Pistachios',                 defaultServing: 28,  unitLabel: '~49 nuts',         calories: 159, protein: 5.7,  carbs: 7.7,  fat: 12.8 },
  { name: 'Macadamia Nuts',             defaultServing: 28,  unitLabel: '~10 nuts',         calories: 204, protein: 2.2,  carbs: 3.9,  fat: 21.5 },
  { name: 'Pecans',                     defaultServing: 28,  unitLabel: '~19 halves',       calories: 196, protein: 2.6,  carbs: 4.0,  fat: 20.4 },

  // ── Baked Goods & Desserts ───────────────────────────────────────────────
  { name: 'Banana Bread (1 slice)',     defaultServing: 60,  unitLabel: '1 slice',          calories: 196, protein: 3.0,  carbs: 33.0, fat: 6.0  },
  { name: 'Brownie',                    defaultServing: 56,  unitLabel: '1 piece',          calories: 227, protein: 3.0,  carbs: 36.0, fat: 9.0  },
  { name: 'Chocolate Chip Cookie',      defaultServing: 16,  unitLabel: '1 cookie',         calories: 78,  protein: 1.0,  carbs: 11.0, fat: 3.6  },
  { name: 'Cheesecake',                 defaultServing: 100, unitLabel: '1 slice',          calories: 321, protein: 5.5,  carbs: 25.6, fat: 22.5 },
  { name: 'Cinnamon Roll',              defaultServing: 100, unitLabel: '1 roll',           calories: 349, protein: 5.0,  carbs: 56.0, fat: 12.0 },
  { name: 'Donut (glazed)',             defaultServing: 60,  unitLabel: '1 donut',          calories: 253, protein: 2.9,  carbs: 38.0, fat: 11.0 },
  { name: 'Scone',                      defaultServing: 90,  unitLabel: '1 scone',          calories: 370, protein: 6.0,  carbs: 56.0, fat: 13.0 },

  // ── Fermented & Functional Foods ────────────────────────────────────────
  { name: 'Kefir (plain)',              defaultServing: 240, unitLabel: '1 cup',            calories: 104, protein: 9.0,  carbs: 11.6, fat: 2.5  },
  { name: 'Miso Paste',                 defaultServing: 17,  unitLabel: '1 tbsp',           calories: 34,  protein: 2.2,  carbs: 4.3,  fat: 1.0  },
  { name: 'Sauerkraut',                 defaultServing: 100, calories: 19,  protein: 0.9,  carbs: 4.3,  fat: 0.1 },
]
